CREATE TABLE IF NOT EXISTS seo_hidden_attributes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item_id VARCHAR(50) NOT NULL,
    account_id INT UNSIGNED NOT NULL,
    category_id VARCHAR(20) NOT NULL,
    attribute_id VARCHAR(50) NOT NULL,
    attribute_name VARCHAR(255) NOT NULL,
    attribute_type VARCHAR(50) NOT NULL,
    frequency INT NOT NULL DEFAULT 0,
    competitor_count INT NOT NULL DEFAULT 0,
    impact_level ENUM('high', 'medium', 'low') NOT NULL DEFAULT 'low',
    suggested_values JSON NULL,
    value_distribution JSON NULL,
    requires_validation TINYINT(1) NOT NULL DEFAULT 0,
    is_technical TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('detected', 'pending', 'applied', 'rejected') NOT NULL DEFAULT 'detected',
    detected_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    applied_at TIMESTAMP NULL DEFAULT NULL,
    applied_by INT UNSIGNED NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_item_attribute (item_id, attribute_id),
    INDEX idx_account_item (account_id, item_id),
    INDEX idx_category (category_id),
    INDEX idx_status (status),
    INDEX idx_impact (impact_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
